export const actionHelpText = {
  dashboard: "Go to your dashboard",
  navigationDashboard: "Open Dashboard",
  searchEverything: (shortcut: string) =>
    `Find a tab, desktop, saved link, or webpage. Keyboard shortcut: ${shortcut}`,
  desktopList: (name: string) => `Open the desktop list. You are currently in ${name}`,
  dashboardOverview: "See an overview of this desktop and continue where you left off",
  browse: "Browse the web or type a website address",
  canvasPages: "Open your visual notes and connected pages",
  runnableApps: "Open Daily Flow, Pomodoro, Wealth Lab, and your other tools",
  savedLinks: "See webpages you have saved",
  readingQueue: "See webpages you want to read later",
  settings: "Change how Coach Browser looks and works",
  profiles: "Choose a browsing profile or change its privacy settings",
  connectObsidian: "Connect Obsidian to save webpages as notes",
  workspaceMenu: "Manage your profiles, desktops, tabs, and settings",
  compactNavigation: "Hide the full sidebar and use the smaller icon menu",
  addDesktop: "Create a separate space for another group of tabs and saved links",
  desktop: (name: string) => `Go to ${name} and continue where you left off`,
  desktopDashboard: (name: string) => `Open ${name} Dashboard`,
  showAllOpenTabs: "Show all open tabs",
  newDashboardTab: "Open a new tab",
  dashboardTabGrid: "Show open tabs as cards",
  dashboardTabList: "Show open tabs as a list",
  openDashboardTab: (name: string) => `Open ${name}`,
  pinDashboardTab: (name: string, pinned: boolean) =>
    pinned ? `Remove ${name} from pinned tabs` : `Keep ${name} pinned for quick access`,
  favoriteDashboardTab: (name: string, favorite: boolean) =>
    favorite ? `Remove ${name} from Favorites` : `Save ${name} to Favorites`,
  moveDashboardTab: (name: string) => `Drag ${name} to change its position`,
  closeDashboardTab: (name: string) => `Close ${name}`,
  renameDesktop: (name: string) => `Change the name of ${name}`,
  archiveDesktop: (name: string) =>
    `Move ${name} out of the sidebar without deleting its saved information`,
  addressBar: "Type a website address or search term, then press Enter",
  dashboardCustomization: (open: boolean) =>
    open ? "Close dashboard customization" : "Choose what appears on your dashboard",
  newTabSearch: "Type a website address or search term, then press Enter or choose Search",
  newTabSearchButton: "Search the web or open this address",
  newTabShortcut: (name: string) => `Open ${name}`,
  manageNewTabShortcuts: "Open saved links to add or manage shortcuts",
  continueNewTabItem: (name: string) => `Continue with ${name}`,
  viewNewTabHistory: "Open your dashboard to see more recent work",
  quickAccess: (name: string) => `Open ${name}`,
  quickCaptureNote: "Type a note to save in your Daily Flow Inbox",
  captureQuickNote: "Save this note in your Daily Flow Inbox",
  openQuickCaptureInbox: "Open your Daily Flow Inbox",
  commandSearch: "Type to find a tab, desktop, saved link, app command, or webpage",
  dashboardSection: (name: string) => `Show ${name} on the dashboard`,
  dashboardSectionToggle: (name: string, shown: boolean) =>
    shown ? `Hide ${name} from the dashboard` : `Show ${name} on the dashboard`,
  dashboardSectionDrag: (name: string) => `Drag ${name} to move it on the dashboard`,
  closeDashboardCustomization: "Close dashboard customization",
} as const;
